config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", confirmations: 'users/confirmations'}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'pages/index'
	root "pages#index"
  #get "/pages/:show/:mainid/:category_id" => "blogs#category", as: :blogs_category
  get "/search" => "products#search"

  get "/ajaxValidateFieldUser" => "dashboard#verify_password"


  get "/about" => "pages#about"
  get "/how-we-work" => "pages#how_we_work"
  get "/wishlist" => "pages#wishlist"

  # get "/services" => "pages#services"
  get "/careers" => "pages#careers"
  get "/contact-us" => "pages#contact_us"
  post "/contact-us" => "pages#contact_us_submit"


  post "/quote" => "pages#quote", as: :quote
  post "/news_letter" => "pages#news_letter"
  get "/unsubscribe/:code" => "pages#unsubscribe"
  get "/sitemap" => "pages#sitemap"
  post "/get_in_touch" => "pages#get_in_touch"

  scope "blogs" do
    get "/" => "blogs#index"
    get "/:id" => "blogs#show", as: :blog
    get "/category/:service_category_id" => "blogs#service_category", as: :blogs_service_category
    get "/category/:service_category_id/:main_category_id" => "blogs#main_category", as: :blogs_main_category
    get "/category/:service_category_id/:main_category_id/:category_id" => "blogs#category", as: :blogs_category
  end

  resources :carts, only: :index do
    post :add_item
    post :update_item
    post :update_item_comment
    delete :delete_item_doc
    delete :remove_item
    get :review
    get :payment
    get :set_address
    get :edit_address
    get :new_address
    post :update_address
    get :set_billing_address
    get :new_billing_address
    get :edit_billing_address
    post :update_billing_address
  end

  resources :orders, only: :create

  resources :categories, only: :index do
    get "products"
    get "quote"
    post "custom_quote"
    get "get_main_categories"
    get "get_categories"

    get "/:main_category_id/:category_id/products" => "categories#products"
    get "/:main_category_id/:category_id/quote" => "categories#quote"


    # get "/get_main_category/:service_category_id" => "categories#get_main_category"
  end

  resources :products, only: :show do
  end

  get "/products/:service_category_id/:main_category_id/:category_id/:id" => "products#show", as: :show

  # scope "categories" do
  #   get "/:id/products" => "categories#products", as: :products
  # end
  

  namespace :dashboard do
    get '', action: :index
    post '/profile_pic/update', action: :update_profile_pic, as: :update_profile_pic
    post '/profile/update', action: :update_profile, as: :update_profile
    post '/mobile/update', action: :update_mobile, as: :update_mobile
    post '/otp/verify', action: :verify_otp, as: :verify_otp

    post '/update_password', action: :update_password, as: :update_password

    get "/address/new", action: :new_address, as: :new_address
    get "/address/:id/edit", action: :edit_address, as: :edit_address
    post '/address/create', action: :create_address, as: :create_address
    get "/address/:id/set_default_address", action: :set_default_address, as: :set_default_address
    delete "/address/:id", action: :delete_address, as: :delete_address
    post "create_vendor"
    post :business_profile
    post :expertise
    post :capacity
    post :legal

    get :new_project
    get "/project/:id/edit", action: :edit_project, as: :edit_project
    post :projects
    delete "/project/:id/edit", action: :delete_project, as: :delete_project

    get :new_employment
    get "/employment/:id/edit", action: :edit_employment, as: :edit_employment
    post :employments
    delete "/employment/:id/edit", action: :delete_employment, as: :delete_employment

    get :new_education
    get "/education/:id/edit", action: :edit_education, as: :edit_education
    post :educations
    delete "/education/:id/edit", action: :delete_education, as: :delete_education

    post "/wishlist/:id", action: :add_wishlist, as: :add_wishlist
    post "/deactivate", action: :deactivate, as: :deactivate
    post "/reactivate", action: :reactivate, as: :reactivate


  end

  resources :vendors do
    post :update
  end


  delete "remove_wishlist_item/:slug" => "dashboard#remove_wishlist_item", as: :remove_wishlist_item
  

  get "/get_states/:country" => "pages#get_states"
  get "/get_cities/:state/:country" => "pages#get_cities"
  get '/dashboard/preview_profile'
  get '/carts/payment'
  get '/career/:id' => "pages#career"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  before_action :authenticate_user!, except: [:add_wishlist]
  before_action :set_current_user

  def index
  end

  def update_profile_pic
    @user.update(user_params)
    redirect_to params[:user][:url]
  end

  def update_profile
  	if @user.update(user_params)
      flash.now[:success] = "Your profile has been updated successfully!"
      if params[:user][:user_type] == "vendor"
        redirect_to "#{dashboard_path}?user_type=#{params[:user][:user_type]}"
      else
        redirect_to dashboard_path
      end
    else
      flash.now[:error] = "Your profile has not been updated!"
      render "index"
    end
  end

  def update_mobile
    @user.errors.add(:mobile, "has already been taken") if @user.mobile == params[:user][:mobile]
  	if @user.errors.blank? && @user.update(user_params)
      @user.generate_otp
      @is_updated = true
    end
  end

  def verify_otp
    @user.errors.add(:otp, "incorrect") if @user.otp != params[:user][:otp]
    @user.errors.add(:password, "incorrect") unless @user.valid_password?(params[:user][:password])
    if @user.errors.blank? && @user.verify_otp
      @is_updated = true
      flash.now[:success] = "Your mobile has been verified successfully!"
    else
      flash.now[:error] = "Your mobile has not been verified!"
    end
  end

  def verify_password
    if @user.valid_password?(params[:fieldValue])
      render json: ["user_old_password", true , ""]
    else
      render json: ["user_old_password", false , "The old password is wrong"]
    end
  end

  def update_password
    if params[:user][:password] == params[:user][:password_confirmation]
      @user.update(password: params[:user][:password])
      flash[:success] = "Password has been successfully changed!"
      redirect_to dashboard_path
    end
  end

  def new_address
    @address = Address.new
    set_new_address
    render "edit_address"
  end

  def edit_address
    @address = Address.find(params[:id])
    set_edit_address(@address.country, @address.state)
  end

  def create_address
    if @user.update(user_params)
      flash[:success] = "Your address has been updated successfully!"
    else
      flash[:error] = "Your address has not been updated!"
    end
    redirect_to dashboard_path
  end

  def set_default_address
    @address = Address.find(params[:id])
    if @address.user == current_user
      current_user.addresses.update_all(is_default: false)
      @address.update(is_default: true)
      flash[:success] = "Your address has been updated successfully!"
    else
      flash[:error] = "Your address has not been updated!"
    end
    redirect_to dashboard_path
  end

  def delete_address
    @address = Address.find(params[:id])
    if @address.user == current_user && @address.present?
      @address.destroy
      flash[:success] = "Your address has been deleted successfully!"
    else
      flash[:error] = "Your address can not be deleted!"
    end
    redirect_to dashboard_path
  end

  def create_vendor
    if @user.update(is_vendor: true, vendor_created_at: Time.now)
      flash[:success] = "You successfully became a Vendor!"
      redirect_to dashboard_path(user_type: "vendor")
    else
      flash[:error] = "You cannot become a Vendor!"
      redirect_to dashboard_path
    end
  end

  def expertise
    if @user.update(user_params)
      flash.now[:success] = "Your expertise has been updated successfully!"
    else
      flash.now[:error] = "Your expertise has not been updated!"
    end
  end

  def business_profile
    if @user.update(user_params)
      flash.now[:success] = "Your Business Profile has been updated successfully!"
    else
      flash.now[:error] = "Your Business Profile has not been updated!"
    end
  end

  def legal
    if @user.update(user_params)
      # @user.vendor_legal.update(legal_areas: params[:user][:legal_attributes][:legal_areas].split)
      flash.now[:success] = "Your legal has been updated successfully!"
    else
      flash.now[:error] = "Your legal has not been updated!"
    end
  end

  def capacity
    if @user.update(user_params)
      flash.now[:success] = "Your capacity has been updated successfully!"
    else
      flash.now[:error] = "Your capacity has not been updated!"
    end
  end

  def new_project
    @project = Project.new
    set_new_address
    render "edit_project"
  end

  def edit_project
    @project = Project.find(params[:id])
    set_edit_address(@project.country, @project.state)
  end

  def projects
    if @user.update(user_params)
      flash.now[:success] = "Your project has been updated successfully!"
    else
      flash.now[:error] = "Your project has not been updated!"
    end
  end

  def delete_project
    @project = Project.find(params[:id])
    if @project.destroy
      flash.now[:success] = "Your project has been deleted successfully!"
    else
      flash.now[:error] = "Your project has not been deleted!"
    end
    render "projects"
  end

  def new_employment
    @employment = Employment.new
    render "edit_employment"
  end

  def edit_employment
    @employment = Employment.find(params[:id])
  end

  def employments
    if @user.update(user_params)
      flash.now[:success] = "Your employment has been updated successfully!"
    else
      flash.now[:error] = "Your employment has not been updated!"
    end
  end

  def delete_employment
    @employment = Employment.find(params[:id])
    if @employment.destroy
      flash.now[:success] = "Your employment has been deleted successfully!"
    else
      flash.now[:error] = "Your employment has not been deleted!"
    end
    render "employments"
  end

  def new_education
    @education = Education.new
    render "edit_education"
  end

  def edit_education
    @education = Education.find(params[:id])
  end

  def educations
    if @user.update(user_params)
      flash.now[:success] = "Your education has been updated successfully!"
    else
      flash.now[:error] = "Your education has not been updated!"
    end
  end

  def delete_education
    @education = Education.find(params[:id])
    if @education.destroy
      flash.now[:success] = "Your education has been deleted successfully!"
    else
      flash.now[:error] = "Your education has not been deleted!"
    end
    render "educations"
  end

  def add_wishlist
    @product = Product.find(params[:id])
    if user_signed_in?
      existing_wishlist = current_user.wishlists.where(product_id: @product.id)
      if existing_wishlist.present?
        flash.now[:error] = "Product is already in your Wishlist!"
      else
        current_user.wishlists.create(product_id: @product.id)
        flash.now[:success] = "Product has been added to your Wishlist!"
      end
    else
      flash[:error] = "You need to sign in or sign up before continuing."
    end
  end

  def remove_wishlist_item
    @product = Product.find_by(slug: params[:slug])
    current_user.wishlists.where(product_id: @product.id).first.destroy
    flash[:success] = "Product is removed from your wishlists"
    respond_to do |format|
      format.html { redirect_to(wishlist_url) }
      format.js
    end
  end

  def deactivate
    if @user.update(is_vendor: false)
      flash[:success] = "You successfully deactivated your seller profile!"
    else
      flash[:error] = "You cannot deactivate your seller profile!"
    end
    redirect_to dashboard_path
  end

  def reactivate
    if @user.update(is_vendor: true)
      flash[:success] = "You successfully reactivated your seller profile!"
    else
      flash[:error] = "You cannot reactivate your seller profile!"
    end
    redirect_to dashboard_path
  end

  private

    def set_new_address
      @countries = CS.countries.map{|c| [c.last, c.last]}
      country_code = CS.countries.to_a.select{|i| i[1] == "India"}[0][0]
      @states_hash = CS.states(country_code)
      @states_hash[:AN] = "Andaman and Nicobar Islands"
      @states_hash[:PY] = "Puducherry"
      @states_hash[:CT] = "Chhattisgarh"
      @states_hash[:HP] = "Himachal Pradesh"
      @states_hash[:JH] = "Jharkhand"
      @states_hash[:PB] = "Punjab"
      @states_hash[:DL] = "Delhi"
      @states_hash[:LD] = "Lakshadweep"
      @states = CS.states(country_code).map{|c| [c.last, c.last]}
      @cities = {}
    end

    def set_edit_address(country, state)
      country = "India" if country.nil?
      state = "Delhi" if state.nil?
      @countries = CS.countries.map{|c| [c.last, c.last]}
      country_code = CS.countries.to_a.select{|i| i[1] == country}[0][0]
      @states_hash = CS.states(country_code)
      @states = CS.states(country_code).map{|c| [c.last, c.last]}
      if country == "India"
        state_code = :AN if state == "Andaman and Nicobar Islands"
        state_code = :PY if state == "Puducherry"
        state_code = :CT if state == "Chhattisgarh"
        state_code = :HP if state == "Himachal Pradesh"
        state_code = :JH if state == "Jharkhand"
        state_code = :PB if state == "Punjab"
        state_code = :DL if state == "Delhi"
        state_code = :LD if state == "Lakshadweep"
      else
        state_code = @states_hash.to_a.select{|i| i[1] == state}[0][0]
      end
      @cities = CS.cities(state_code, country_code)
    end

    def set_current_user
      @user = current_user
      @is_updated = false
    end

    def user_params
      params.require(:user).permit(:first_name, :last_name, :linkedin, :facebook, :twitter, :google, :pintrest, :instagram, :image, :mobile, :vendor_type, :country_code,
        profile_attributes: [:gender, :dob, :marital_status, :website],
        expertise_attributes: [:id, :name, :credentials, :desc, :tagline, :certifications, :certification_number, :describe => [], :expertise_areas => []],
        business_profile_attributes: [:company_name, :owner_ceo_name, :owner_ceo_mobile, :landline, :logo, :linkedin, :facebook, :twitter, :google, :pintrest, :instagram],

app/views/dashboard/_capacity.html.erb
<div class="dash-data profile tmp-hide" id="capacity-section">
	<%= form_for @user, url: dashboard_capacity_path, method: :post, remote: true do |f| %>
	  <div class=" container border-bottom text-center">
			<h1 class="xlarge dark ">
				Capacity
				<!-- <span class="edit editstyle text-right" id="editbutt"><i class="fa fa-edit medium ic">Edit</i></span> -->
				<%= f.submit "Save Changes", class: "save btn-primary pull-right" %>
			</h1>
		</div>
		<div class="dash-main container">
			<%= f.fields_for :capacity, @user.capacity || Capacity.new do |c| %>
				<%= render "common/capacity_form", c: c %>
			<% end %></br>
			<p> Note: “You can fill up these fields any time. The fields marked with * are required to be filled before profile submission.”</p>
		</div>
	<% end %>
</div>

app/views/dashboard/_education_form.html.erb
<div class="modal-dialog modal-dialog-centered">
  <div class="modal-content">
    <div class="modal-header">
      <h3 class="modal-title text-center">Add Education</h3>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <%= form_for @user, url: dashboard_educations_path, method: :post, remote: true do |f| %>
      <div class="modal-body">
        <div class="col-md-12">
          <div class=" panel-default">
            <div class="panel-body">
              <div class="">
                <div class="panel-body">
                  <fieldset>
                    <%= f.fields_for :educations, education do |e| %>
                      <%= render "common/education_form", e: e %>
                    <% end %>
                  </fieldset>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer" style="justify-content: center;">
        <%= f.submit "Submit", class: "btn btn-primary" %>
      </div>
    <% end %></br>
      <!-- <p> Note: “You can fill up these fields any time. The fields marked with * are required to be filled before profile submission.”</p> -->
  </div>
</div>

app/views/dashboard/_projects.html.erb
<div class="dash-data mobile-dash-data" id="project-section" style="display: block;">
  <div class=" container border-bottom text-center">
    <h1 class="xlarge dark">Projects</h1>
  </div>
  <div class="dash-main">
    <div class="dash-row large dark ">
      <div class="container">
        <%= link_to dashboard_new_project_path, remote: true, class: "button width100" do %>
          <span class="fa fa-plus"></span> Add Project
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="address row">
        <% projects.each do |project| %>
          <div class="col-md-12">
            <div class="add1">
              <div class="address-container">
                <div class="row">
                  <div class="col-md-4 text-left">
                    <div><span class="badge badge-secondary"><%= project.type %></span></div><br>
                  </div>
                  <div class="col-md-8 text-right">
                    <strong>
                      <%= link_to "Edit", dashboard_edit_project_path(project), remote: true %>
                      &nbsp;|&nbsp;
                      <%= link_to "Delete", dashboard_delete_project_path(project), data: {method: :delete, confirm: "Are you sure?", remote: true} %>
                    </strong>
                  </div>
                </div>
                <div>
                  <div>
                    <strong><%= project.name %></strong>&nbsp;
                    <strong><%= project.developer %></strong>
                  </div><br>
                   <div>Location: <%= project.location %></div><br>
                  <div>Configuration (No of floors): <%= project.configuration %></div><br>
                  <div>Completion Date: <%= project.completion_date %></div><br>
                  <div>Star Rating: <%= project.star_rating %></div><br>
                  <div>Description: <%= project.desc %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="modal" id="project-popup" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/dashboard/index.html.erb
<div class="path-fixed">
  <div class="container">
    <div class="row">
      <div class="col-md-4 pt-1"></div>
      <div class="col-md-4 pt-1 text-center">
        <h1 class="text-center" style="font-size:30px;"><%#= current_dashboard_type %> Dashboard</h1>
      </div>
      <%# if current_dashboard_type == "Partner" %>
      <% if current_user.is_vendor? %>
        <!-- <div class="col-md-4 d-flex justify-content-end align-items-center">
          <%#= link_to "Preview Profile", '/dashboard/preview_profile', class: "btn btn-primary" %>
        </div> -->
      <% end %>
    </div>
  </div>
</div>


<div class="container dashboard pb-40 pt-100">
  <%# if current_dashboard_type == "Partner" %>
  <% if current_user.is_vendor? %>
    <div class="text-right">
      <div class="medium dark">
        Profile Status - <%= User::VENDOR_STATUS[current_user.vendor_status] %>
        <% if @user.date.present? %>
          <br>Date:  <%= @user.date.strftime("%d/%b/%Y") %>
        <% end %>
      </div>
    </div>
    <br>
  <% end %> 


  <div class="dashboard-container mobile-dashboard-container">
    <div class="col-xs-12">
      <%= render "sidebar" %>
    </div>
    <div class="col-xs-12" style="width:100%;">
      <div class="dash-data profile mobile-dash-data" id="butt1data">  
        <div class="dash-main">
          <%= form_for @user, url: dashboard_update_profile_path, html: {id: "information_form"}, method: :post do |f| %>
            <%= f.hidden_field :user_type, value: params[:user_type] %>
            <div class="container">
              <div class="row col-lg-12">
                <span>
                  <h4>
                    User Information&nbsp;
                    <span class="edit editstyle" id="editbutt"><i class="fa fa-edit large ic"></i>Edit</span>
                    <%= f.submit "Save Changes", class: "save tmp-hide btn-primary" %>
                  </h4>
                </span>
              </div>
            </div>

            <%# if current_dashboard_type == "Partner" %>
            <% if current_user.is_vendor? %>
              <div class="container">
                <div class="row">
                  <div class="fieldcontainer col-lg-6">
                    <h6>Incorporation Status</h6>
                    <%#= f.collection_radio_buttons :vendor_type, [[1, "<span title='For Freelancers can fill education and employment section' data-toggle='tooltip'>Freelancer</span>".html_safe], [2, "<span title='Company fill the legal section' data-toggle='tooltip'>Company</span>".html_safe]], :first, :last, include_hidden: false %>

                    <%= f.radio_button :vendor_type, 1, disabled: true, class: "namefield" %>
                    <label for="user_vendor_type_1"><span title="" data-toggle="tooltip" data-original-title="For Freelancers can fill education and employment section">Freelancer</span></label>
                    <%= f.radio_button :vendor_type, 2, disabled: true, class: "namefield" %>
                    <label for="user_vendor_type_2"><span title="" data-toggle="tooltip" data-original-title="Company fill the legal section">Company</span></label>


                  </div>
                </div>
              </div>
            <% end %>
            
            <div class="container">
              <div class="row">
                <div class="fieldcontainer col-lg-6">
                  <h6>First Name</h6>
                  <%= f.text_field :first_name, class: "namefield field-box field validate[required]", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Last Name</h6>
                  <%= f.text_field :last_name, class: "namefield field-box", disabled: true %>
                </div>
                <%= f.fields_for :profile, @user.profile || Profile.new do |p| %>
                  <div class="container">
                    <div class="row">
                      <div class="fieldcontainer col-lg-6">
                        <h6>Gender</h6>
                        <%= p.select(:gender, options_for_select([["Male", 1], ["Female", 2]], @user.profile.try(:gender)), {include_blank: "Select Gender"}, {class: "form-control namefield field-box field", disabled: true}) %>
                      </div>
                      <div class="fieldcontainer col-lg-6">
                        <h6>Date of Birth</h6>
                        <%= p.text_field :dob, class: "namefield field-box field datepicker", disabled: true, value: (p.object.dob.strftime("%d/%b/%Y") rescue nil) %>
                      </div>

                      <div class="fieldcontainer col-lg-6">
                        <h6>Marital Status</h6>
                        <%#= p.collection_radio_buttons :marital_status, [[1, "Married"], [2, "Un-married"]], :first, :last, include_hidden: false %>
                        <%= p.radio_button :marital_status, 1, disabled: true, class: "namefield" %>
                        <label for="user_profile_attributes_marital_status_1">Married</label>
                        <%= p.radio_button :marital_status, 2, disabled: true, class: "namefield" %>
                        <label for="user_profile_attributes_marital_status_2">Un-married</label>
                      </div>

                    </div>
                  </div>

                  <%# if current_dashboard_type == "Partner" %>
                  <% if current_user.is_vendor? %>
                    <div class="container">
                      <div class="row">
                        <div class="fieldcontainer col-lg-6">
                          <h6>Website</h6>
                          <%= p.text_field :website, class: "namefield field-box field", disabled: true %>
                        </div>
                        <div class="fieldcontainer col-lg-6">
                        <h6>Country Code</h6>
                        <%= f.select :country_code, ISO3166::Country.all.map{|c| [c.name, "+#{c.country_code}"]}, {}, class: "form-control namefield field-box field", disabled: true %>
                      </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>

                <div class="container">
                  <div class="row">
                    <div class="col-lg-6">
                      <%= render "email" %>
                    </div>
                    <div class="col-lg-6">
                      <%= render "mobile" %>
                    </div>
                  </div>
                </div>
                
                <div class="fieldcontainer col-lg-6">
                  <h6>Linkedin</h6>
                  <%= f.text_field :linkedin, class: "namefield field-box field", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Facebook</h6>
                  <%= f.text_field :facebook, class: "namefield field-box field", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Twitter</h6>
                  <%= f.text_field :twitter, class: "namefield field-box field", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Google</h6>
                  <%= f.text_field :google, class: "namefield field-box field", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Pintrest</h6>
                  <%= f.text_field :pintrest, class: "namefield field-box field", disabled: true %>
                </div>
                <div class="fieldcontainer col-lg-6">
                  <h6>Instagram</h6>
                  <%= f.text_field :instagram, class: "namefield field-box field", disabled: true %>
                </div>
              </div>
            </div>
          <% end %>
          <%= render "change_password" %>
        </div>
      </div>
      <%= render "orders" %>
      <% if current_user.is_company? %>
        <%= render "business_profile" %>
      <% end %>
      <%= render "addresses" %>
      <% if current_user.is_freelancer? %>
        <div id="employments-list">
          <%= render "employments", employments: @user.employments %>
        </div>
      <% end %>
      <% if current_user.is_freelancer? %>
        <div id="educations-list">
          <%= render "educations", educations: @user.educations %>
        </div>
      <% end %>
      <% if current_user.is_company? %>
        <%= render "legal" %>
      <% end %>
      <% if current_user.is_vendor? %>
        <%= render "expertise" %>
      <% end %>
      <% if current_user.is_vendor? %>
        <div id="projects-list">
          <%= render "projects", projects: @user.projects %>
        </div>
      <% end %>
      <% if current_user.is_company? %>
        <%= render "capacity" %>
      <% end %>
    </div>
  </div>
</div>







<div class="modal fade" id="change-email" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-center">Change Email</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(current_user, as: "user", url: registration_path("user"), html: {method: :post, remote: true}) do |f| %>
        <div class="col-md-14">
          <div class="card-body">
            <div class="js_flash_messages"></div>
            <fieldset>
              <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Enter New Email Address", class: "form-control input-lg", required: true %>
              <br>
              <%= f.email_field :confirm_email, placeholder: "Confirm Email Address", class: "form-control input-lg", required: true %>
              <br>
              <%= f.password_field :current_password, placeholder: "Enter your Account Password", class: "form-control input-lg", required: true %>
            </fieldset>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Change Email", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

  




<div class="modal fade" id="change-phone" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-center">Change Mobile Number</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @user, url: dashboard_update_mobile_path, method: :post, remote: true do |f| %>
        <div class="col-md-14">
          <div class="card-body">
            <div class="js_flash_messages"></div>
            <fieldset>
              <%= f.text_field :mobile, placeholder: "Enter New Mobile Number", class: "form-control input-lg", required: true %>
            </fieldset>
          </div>
        </div>
        <div class="modal-footer" style="text-align:center;">
          <%= f.submit "Send OTP", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="verify-otp" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title text-center">Verify Mobile Number</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for @user, url: dashboard_verify_otp_path, method: :post, remote: true do |f| %>
        <div class="col-md-14">
          <div class="card-body">
            <div class="js_flash_messages"></div>
            <fieldset>
              <%= f.text_field :otp, placeholder: "Enter OTP", class: "form-control input-lg", required: true %>
              <br>
              <%= f.password_field :password, placeholder: "Enter your Account Password", class: "form-control input-lg", required: true %>
            </fieldset>
          </div>
        </div>
        <div class="modal-footer">
          <%= f.submit "Change Number", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>




<style type="text/css">
  .btn {
    padding: 9px 8px;
  }
  .btn_style a:hover
  {
    color: white;
  }
</style>

<script type="text/javascript">
  $("#information_form").validationEngine();

</script>