config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", confirmations: 'users/confirmations'}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'pages/index'
	root "pages#index"
  #get "/pages/:show/:mainid/:category_id" => "blogs#category", as: :blogs_category
  get "/search" => "products#search"

  get "/ajaxValidateFieldUser" => "dashboard#verify_password"


  get "/about" => "pages#about"
  get "/how-we-work" => "pages#how_we_work"
  get "/wishlist" => "pages#wishlist"

  # get "/services" => "pages#services"
  get "/careers" => "pages#careers"
  get "/contact-us" => "pages#contact_us"
  post "/contact-us" => "pages#contact_us_submit"


  post "/quote" => "pages#quote", as: :quote
  post "/news_letter" => "pages#news_letter"
  get "/unsubscribe/:code" => "pages#unsubscribe"
  get "/sitemap" => "pages#sitemap"
  post "/get_in_touch" => "pages#get_in_touch"

  scope "blogs" do
    get "/" => "blogs#index"
    get "/:id" => "blogs#show", as: :blog
    get "/category/:service_category_id" => "blogs#service_category", as: :blogs_service_category
    get "/category/:service_category_id/:main_category_id" => "blogs#main_category", as: :blogs_main_category
    get "/category/:service_category_id/:main_category_id/:category_id" => "blogs#category", as: :blogs_category
  end

  resources :carts, only: :index do
    post :add_item
    post :update_item
    post :update_item_comment
    delete :delete_item_doc
    delete :remove_item
    get :review
    get :payment
    get :set_address
    get :edit_address
    get :new_address
    post :update_address
    get :set_billing_address
    get :new_billing_address
    get :edit_billing_address
    post :update_billing_address
  end

  resources :orders, only: :create

  resources :categories, only: :index do
    get "products"
    get "quote"
    post "custom_quote"
    get "get_main_categories"
    get "get_categories"

    get "/:main_category_id/:category_id/products" => "categories#products"
    get "/:main_category_id/:category_id/quote" => "categories#quote"


    # get "/get_main_category/:service_category_id" => "categories#get_main_category"
  end

  resources :products, only: :show do
  end

  get "/products/:service_category_id/:main_category_id/:category_id/:id" => "products#show", as: :show

  # scope "categories" do
  #   get "/:id/products" => "categories#products", as: :products
  # end
  

  namespace :dashboard do
    get '', action: :index
    post '/profile_pic/update', action: :update_profile_pic, as: :update_profile_pic
    post '/profile/update', action: :update_profile, as: :update_profile
    post '/mobile/update', action: :update_mobile, as: :update_mobile
    post '/otp/verify', action: :verify_otp, as: :verify_otp

    post '/update_password', action: :update_password, as: :update_password

    get "/address/new", action: :new_address, as: :new_address
    get "/address/:id/edit", action: :edit_address, as: :edit_address
    post '/address/create', action: :create_address, as: :create_address
    get "/address/:id/set_default_address", action: :set_default_address, as: :set_default_address
    delete "/address/:id", action: :delete_address, as: :delete_address
    post "create_vendor"
    post :business_profile
    post :expertise
    post :capacity
    post :legal

    get :new_project
    get "/project/:id/edit", action: :edit_project, as: :edit_project
    post :projects
    delete "/project/:id/edit", action: :delete_project, as: :delete_project

    get :new_employment
    get "/employment/:id/edit", action: :edit_employment, as: :edit_employment
    post :employments
    delete "/employment/:id/edit", action: :delete_employment, as: :delete_employment

    get :new_education
    get "/education/:id/edit", action: :edit_education, as: :edit_education
    post :educations
    delete "/education/:id/edit", action: :delete_education, as: :delete_education

    post "/wishlist/:id", action: :add_wishlist, as: :add_wishlist
    post "/deactivate", action: :deactivate, as: :deactivate
    post "/reactivate", action: :reactivate, as: :reactivate


  end

  resources :vendors do
    post :update
  end


  delete "remove_wishlist_item/:slug" => "dashboard#remove_wishlist_item", as: :remove_wishlist_item
  

  get "/get_states/:country" => "pages#get_states"
  get "/get_cities/:state/:country" => "pages#get_cities"
  get '/dashboard/preview_profile'
  get '/carts/payment'
  get '/career/:id' => "pages#career"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="card-body card-block">
    <div id="error_explanation">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>
      <% resource.errors.full_messages.each do |message| %>
        <div class="text-danger"><%= message %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_flash_messages.html.slim
.flash_msg
  - flash.each do |key, value|
    - unless key == "errors"
      .fade.in
        a.close href="#" data-dismiss="alert"
          .span.remove-flash-msg ×
        .flash-heading
          / = image_tag "tick1.png"
        .flash-content
          - if key == 'alert' || key == 'error'
            .flash-icon
              span.glyphicon.glyphicon-remove
          - elsif key == 'success'
            .flash-icon
              span.glyphicon.glyphicon-ok
          - elsif key == 'notice'
            .flash-icon
              span.glyphicon.glyphicon-info-sign
          - else    
          = value

app/views/shared/_footer.html.erb
<footer class="footer dark-bg page-section-pt8">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-2 col-sm-6 mb-30 mobile-footer">
        <div class="footer-link mobile-footer-link">
          <div class="section-title mobile-title">
            <h4 class="title">Company</h4>
          </div>
          <ul class="list-mark">
            <li><a href="/">Home</a></li>
            <li><a href="/about">About Us</a></li>
            <li><a href="/how-we-work">Our Process</a></li>
            <li><a href="/careers">Careers</a></li>
            <!-- <li><a href="/contact-us">Contact Us</a></li> -->
            <li><a href="/blogs">Blog</a></li>
          </ul>
        </div>
      </div>
      <div class="col-lg-2 col-md-2 col-sm-6 mb-30 mobile-footer">
        <div class="footer-link mobile-footer-link">
          <div class="section-title mobile-title">
            <h4 class="title">Account</h4>
          </div>
          <ul class="list-mark">
            <li><%= link_to "My Account", dashboard_path %></li>
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Cart", "/carts" %></li>
            <li><%= link_to "Wishlist", "/wishlist" %></li>
            <li><%= link_to "Be a Seller", "#{user_signed_in? ? dashboard_path(user_type: 'vendor') : new_user_registration_path}" %></li>
          </ul>
        </div> 
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6 mb-30 mobile-footer">
        <div class="footer-newsletter">
          <div class="section-title mobile-title">
            <h4 class="title">Newsletter</h4>
          </div>
          <%= form_tag news_letter_path, remote: true, id: "newsLetterForm" do |f| %>
            <div class="input-group divcenter"> 
              <%= email_field_tag :email, current_user.try(:email), class: "form-control", required: true, placeholder: "Enter your Email" %>
              <span class="input-group-btn">
              <button type="submit" class="btn btn-icon"><i class="fa fa-paper-plane"></i></button>
              </span>
            </div>
          <% end %>
        </div>
        <div class="footer-social mt-40 text-white mobile-footer">
          <div class="section-title mobile-title">
            <h4 class="title mb-20">Stay Connected</h4>
          </div>
          <div class="social-icons color-hover">
            <ul>
              <li class="social-facebook"><a href="https://www.facebook.com/makemebuilder" target="blank"><i class="fa fa-facebook"></i></a></li>
              <li class="social-twitter"><a href="https://www.twitter.com/makemebuilder" target="blank"><i class="fa fa-twitter"></i></a></li>
              <li class="social-linkedin"><a href="https://www.linkedin.com/company/make-me-builder" target="blank"><i class="fa fa-linkedin"></i></a></li>
              <li class="social-instagram"><a href="https://www.instagram.com/makemebuilder" target="blank"><i class="fa fa-instagram"></i></a></li>
              <li class="social-youtube"><a href="https://www.youtube.com/channel/UCgAT37ZKm9z8F7CgLdkuHkQ" target="blank"><i class="fa fa-youtube-play"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-4 col-sm-6 mb-30 mobile-footer">
        <div class="footer-address">
          <div class="section-title mobile-title">
            <h4 class="title">Get in Touch</h4>
          </div>
          <ul class="list-inline">
            <li>
              <i class="fa fa-map-marker"></i>
              <span><%= raw Contact.first.location rescue nil %></span>
              <!-- <span>Multiple convenient locations in NCR.<br>Contact for appointment.</span> -->
            </li>
            <li>
              <i class="fa fa-phone"></i>
              <span><%= raw Contact.first.call rescue nil %></span>
              <!-- <span><a href="tel:+919810089232" class="color1">+91 9667991921</a></span> -->
              <!-- <span><a href="tel:+91 9471011679" class="color1" >+91 9667991922</a></span> -->
            </li>
            <%#= form_tag get_in_touch_path, remote: true, id: "getintouchForm" do |f| %>
              <!-- <div class="input-group divcenter"> 
                <%= email_field_tag :email, current_user.try(:email), class: "form-control", required: true, placeholder: "Enter your Email" %>
                <span class="input-group-btn">
                <button type="submit" class="btn btn-icon"><i class="fa fa-paper-plane"></i></button>
                </span>
              </div> -->
            <%# end %>
            <li>
              <div>
                <a href="/contact-us" class="button border animated middle-fill get-a-quote-btn">
                  <span>Contact Us</span>
                </a>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="footer-widget mt-20">
    <div class="container">
      <div class="row">
        <div class="col-lg-5 col-md-5 col-sm-5">
          <p class="text-white"> &copy; <span id="copyright"> <%= Date.today.year %></span> <a href="/" class="text-primary"> Make Me Builder, OPC Pvt. Ltd.</a> All Rights Reserved </p>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
          <!-- <p class="text-white">Website Technology Developed by <a href="https://www.abistrategy.com" class="text-primary"><%= image_tag "abi_logo.png", width: 35 %></a></p> -->
        </div>
        <div class="col-lg-4 col-md-4 col-sm-4">
          <ul class="text-right">
            <li><a href="/TermsOfUse.pdf">Terms of Use</a></li>
            <li><a href="/PrivacyPolicy.pdf">Privacy Policy</a></li>
            <li><a href="/sitemap">Site Map</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</footer>

<style type="text/css">
  @media (max-width: 991px){
    .footer .section-title h4.title:after{
      content: "+";
      cursor: pointer;
      display: block;
      font-weight: 700;
      font-family: FontAwesome;
      font-size: 18px;
      position: absolute;
      right: 16px;
      top: 50%;
      margin-top: -20px;
      color: #fff;
      vertical-align: middle;
    }
    .footer .section-title.active h4.title:after{
      content: "-";
    }
    .footer .list-mark{
      display:none;
      overflow: hidden;
    }
    .footer #newsLetterForm{
      display: none;
      overflow: hidden;
    }
    .footer .social-icons{
      display: none;
      overflow: hidden;
    }
    .footer .list-inline{
      display: none;
      overflow: hidden;
    } 
    .footer .col{
      margin-bottom:20px; 
    }
    .footer .col.col1{
      padding:0; 
    }

    .footer-newsletter .section-title{
      margin-bottom: 70px;
    }

    .footer-widget ul{
      padding: 0;
    }
  }
  .color1 {
    color: white;
  }
</style>

<script>
  var coll = document.getElementsByClassName("section-title","list-mark","newsLetterForm","social-icons","list-inline");
  var i;

  for (i = 0; i < coll.length; i++) {
    coll[i].addEventListener("click", function() {
      this.classList.toggle("active");
      var content = this.nextElementSibling;
      if (content.style.display === "block"){
        content.style.display = "none";
      }
      else{
        content.style.display = "block";
      }
    });
  }
</script>

app/views/shared/_header.html.erb
<header id="header" class="clean">
  <div class="menu">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars"></i>
    </button>

    <button class="navbar-toggler pull-right" type="button" data-toggle="collapse" data-target="#navbarCollapse-2" aria-controls="navbarCollapse-2" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fa fa-bars"></i>
    </button>


    <nav class="navbar navbar-expand-md bg-dark bg-primary">
      <a href="/" class="navbar-brand">
        <%= image_tag "mmblogo.jpeg", height: 40 %>
      </a>
      <%= form_tag "/search", class: "form-inline mt-2 mt-md-0 col-md-6", id: "search-form", method: :get do |f| %>
        <%= text_field_tag :q, params[:q], class: "form-control mr-sm-2 width100", placeholder: "Search for products and services" %>
        <span class="glyphicon glyphicon-search" onclick="$('#search-form').submit();"></span>
      <% end %>
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button> -->
      <div class="collapse navbar-collapse justify-content-md-right" id="navbarCollapse">
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to current_user.first_name, dashboard_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "nav-link" %>        
            </li>
            <li class="nav-item">
              <% if current_user.is_vendor? %>
                <%= link_to "You are a Seller!", "javascript:void", class: "nav-link" %>
              <% else %>
                <%= link_to "Be a Seller?", "#vendor-type-popup", "data-toggle": :modal, class: "nav-link" %>
              <% end %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Login', new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Be a Seller?", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
          <li class="nav-item">
            <a class="nav-link" href="/wishlist"><i class="fa fa-heart"></i><span class="sr-only">(current)</span><span class="badge wishlists-count"><%= current_user.wishlists.count rescue nil%></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%= carts_path %>"><i class="fa fa-shopping-cart"></i><span class="sr-only">(current)</span><span class="badge"><%= current_cart.cart_items.count rescue nil%></span></a>
          </li>
        </ul>
      </div>
    </nav>
    <nav id="menu" class="mega-menu navbar navbar-expand-md">
      <section class="menu-list-items navbar_size">
        <div class="container111"> 
          <div class="row"> 
            <div class="col-lg-12 col-md-12">

              <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
              </button>

              <button class="navbar-toggler pull-right" type="button" data-toggle="collapse" data-target="#navbarCollapse-2" aria-controls="navbarCollapse-2" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fa fa-bars"></i>
              </button> -->


              <div class="collapse navbar-collapse justify-content-md-right" id="navbarCollapse-2">

                <ul class="menu-links">
                  <% ServiceCategory.active.each do |service_category| %>
                    <li class="main-category <% if params[:scrollto] == "service-category-#{service_category.id}" %>active<% end %>">
                      <a class="color" href="/categories?scrollto=service-category-<%= service_category.id %>&service_category=<%= service_category.id %>"  ><%= service_category.short_name %>  <i class="fa fa-angle-down fa-indicator"></i></a>
                      <div class="drop-down" style="border-top-width: 0px;">
                        <div class="grid-row">
                          <% service_category.main_categories.active.each do |main_category| %>
                            <!-- <div class="grid-col-3"> -->
                              <ul>
                                <li class="dropdown">
                                  <a href="/categories?scrollto=main-category-<%= main_category.id %>&service_category=<%= service_category.id %>"><%= main_category.short_name %></a>
                                  <ul class="dropdown-menu">
                                    <% main_category.categories.active.each do |category| %>
                                      <li>
                                        <%= link_to category.name, category.url %>
                                      </li>
                                    <% end %>
                                   </ul>
                                </li>
                              </ul>
                            <!-- </div> -->
                          <% end %>
                        </div>
                      </div>
                    </li>
                  <% end %>
                </ul>








                <ul class="menu-links pull-right">
                  <li class="main-category">
                    <a class="color" href="/about">About Us</a>
                  </li>
                  <li class="main-category">
                    <a class="color" href="/how-we-work">Our Process</a>
                  </li>
                  <li class="main-category">
                    <a class="color" href="/blogs">Blog</a>
                  </li>
                </ul>

              </div>
            </div>
          </div>
        </div>
      </section>
    </nav>
  </div>
</header>

<style type="text/css">
  .fixed-top-2{
    margin-top: 56px;
  }
  .color:hover{
    color:#ffd800 !important;
  }

  .navbar-expand-md .navbar-collapse.collapse.show .menu-links{
    display: block !important;
    position: relative;
    top: -95px !important;
  }

  #navbarCollapse-2{display: block !important;}

  @media (min-width: 768px){
    button.navbar-toggler{display:none;}
  }

  .mega-menu .menu-links > li:hover{
    background-color: #000;
  }

  .mega-menu .menu-links > li:hover a.color{
    color: #ffd800 !important;
  }

  li.dropdown.open ul{
    display: block;
  }

  li.dropdown:hover ul{
    display: block;
    background: rgba(21, 21, 21, 0.9);
    left: 100%;
    top: 0;
  }
  .drop-down li{
    padding-right: 5px;
  }
  .navbar_size
  {
    height: 50px;
  }
</style>

app/views/shared/_js_flash.html.erb
<%#= devise_error_messages! %>

<% if object.errors.any? %>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>