config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", confirmations: 'users/confirmations'}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'pages/index'
	root "pages#index"
  #get "/pages/:show/:mainid/:category_id" => "blogs#category", as: :blogs_category
  get "/search" => "products#search"

  get "/ajaxValidateFieldUser" => "dashboard#verify_password"


  get "/about" => "pages#about"
  get "/how-we-work" => "pages#how_we_work"
  get "/wishlist" => "pages#wishlist"

  # get "/services" => "pages#services"
  get "/careers" => "pages#careers"
  get "/contact-us" => "pages#contact_us"
  post "/contact-us" => "pages#contact_us_submit"


  post "/quote" => "pages#quote", as: :quote
  post "/news_letter" => "pages#news_letter"
  get "/unsubscribe/:code" => "pages#unsubscribe"
  get "/sitemap" => "pages#sitemap"
  post "/get_in_touch" => "pages#get_in_touch"

  scope "blogs" do
    get "/" => "blogs#index"
    get "/:id" => "blogs#show", as: :blog
    get "/category/:service_category_id" => "blogs#service_category", as: :blogs_service_category
    get "/category/:service_category_id/:main_category_id" => "blogs#main_category", as: :blogs_main_category
    get "/category/:service_category_id/:main_category_id/:category_id" => "blogs#category", as: :blogs_category
  end

  resources :carts, only: :index do
    post :add_item
    post :update_item
    post :update_item_comment
    delete :delete_item_doc
    delete :remove_item
    get :review
    get :payment
    get :set_address
    get :edit_address
    get :new_address
    post :update_address
    get :set_billing_address
    get :new_billing_address
    get :edit_billing_address
    post :update_billing_address
  end

  resources :orders, only: :create

  resources :categories, only: :index do
    get "products"
    get "quote"
    post "custom_quote"
    get "get_main_categories"
    get "get_categories"

    get "/:main_category_id/:category_id/products" => "categories#products"
    get "/:main_category_id/:category_id/quote" => "categories#quote"


    # get "/get_main_category/:service_category_id" => "categories#get_main_category"
  end

  resources :products, only: :show do
  end

  get "/products/:service_category_id/:main_category_id/:category_id/:id" => "products#show", as: :show

  # scope "categories" do
  #   get "/:id/products" => "categories#products", as: :products
  # end
  

  namespace :dashboard do
    get '', action: :index
    post '/profile_pic/update', action: :update_profile_pic, as: :update_profile_pic
    post '/profile/update', action: :update_profile, as: :update_profile
    post '/mobile/update', action: :update_mobile, as: :update_mobile
    post '/otp/verify', action: :verify_otp, as: :verify_otp

    post '/update_password', action: :update_password, as: :update_password

    get "/address/new", action: :new_address, as: :new_address
    get "/address/:id/edit", action: :edit_address, as: :edit_address
    post '/address/create', action: :create_address, as: :create_address
    get "/address/:id/set_default_address", action: :set_default_address, as: :set_default_address
    delete "/address/:id", action: :delete_address, as: :delete_address
    post "create_vendor"
    post :business_profile
    post :expertise
    post :capacity
    post :legal

    get :new_project
    get "/project/:id/edit", action: :edit_project, as: :edit_project
    post :projects
    delete "/project/:id/edit", action: :delete_project, as: :delete_project

    get :new_employment
    get "/employment/:id/edit", action: :edit_employment, as: :edit_employment
    post :employments
    delete "/employment/:id/edit", action: :delete_employment, as: :delete_employment

    get :new_education
    get "/education/:id/edit", action: :edit_education, as: :edit_education
    post :educations
    delete "/education/:id/edit", action: :delete_education, as: :delete_education

    post "/wishlist/:id", action: :add_wishlist, as: :add_wishlist
    post "/deactivate", action: :deactivate, as: :deactivate
    post "/reactivate", action: :reactivate, as: :reactivate


  end

  resources :vendors do
    post :update
  end


  delete "remove_wishlist_item/:slug" => "dashboard#remove_wishlist_item", as: :remove_wishlist_item
  

  get "/get_states/:country" => "pages#get_states"
  get "/get_cities/:state/:country" => "pages#get_cities"
  get '/dashboard/preview_profile'
  get '/carts/payment'
  get '/career/:id' => "pages#career"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord

	acts_as_shopping_cart_using :cart_item

  belongs_to :user

  has_one :order
  PAYMENT = [[1, "Cash on delivery"],[2, "card"],[3, "stripe"],[4, "paypal"]]


  # validates_presence_of :name, :mobile, :address_line_1, :address_line_2, :country, :state, :city, :zip_code

  def tax_pct
    0
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_action :authenticate_user!, except: :add_item

	def index
		
	end

	def add_item
		product = Product.find(params[:cart_item][:product_id])
		unless user_signed_in?
			store_location_for(:user, request.referer)
			flash[:notice] = "You need to sign in or sign up before continuing."
			redirect_to "/users/sign_in"
		else
			cart_item = current_cart.add(product, product.price, params[:cart_item][:quantity].to_i)
			cart_item.update(comment: params[:cart_item][:comment])
			flash[:notice] = "The product has been added to your Cart."
			redirect_to "/carts"
		end
	end

	def update_item
		# cart_item = CartItem.find(params[:cart_item][:cart_item_id])
		@cart_item = CartItem.find(params[:cart_id])

		# cart_item.update(quantity: params[:cart_item][:quantity],comment: params[:cart_item][:comment])
		@cart_item.update(cart_item_params)
		# flash[:notice] = "The item has been updated in your Cart."
		# redirect_to "/carts"
	end

	def update_item_comment
		@cart_item = CartItem.find(params[:cart_id])
		@cart_item.update(cart_item_params)
		render body: nil
	end

	# def update_item_doc
	# 	@cart_item = CartItem.find(params[:cart_id])
	# 	@cart_item.update(cart_item_params)
	# 	# flash[:notice] = "The item has been updated in your Cart."
	# end

	def delete_item_doc
		@cart_item = CartItem.find(params[:cart_id])
		document = @cart_item.documents.find(params[:doc])
		if document.present?
			document.destroy
		end
		# flash[:notice] = "Document has been deleted from your Cart."
		# redirect_to "/carts"
		# @cart_item = CartItem.find(params[:cart_id])
		# @cart_item.update(cart_item_params)
		# flash[:notice] = "The item has been updated in your Cart."
	end

	def remove_item
		cart_item = CartItem.find(params[:cart_id])
		cart_item.destroy
		flash[:notice] = "The item has been removed from your Cart."
		redirect_to "/carts"
	end

	def review
		unless current_cart.is_address_saved
			default_address = current_user.default_address
			if default_address.present?
				current_cart.update(
					name: default_address.name,
					mobile: default_address.mobile,
					email: current_user.email,
					address_line_1: default_address.address_line_1,
					address_line_2: default_address.address_line_2,
					country: default_address.country,
					state: default_address.state,
					city: default_address.city,
					zip_code: default_address.zip_code,

					billing_name: default_address.name,
					billing_mobile: default_address.mobile,
					billing_email: current_user.email,
					billing_address_line_1: default_address.address_line_1,
					billing_address_line_2: default_address.address_line_2,
					billing_country: default_address.country,
					billing_state: default_address.state,
					billing_city: default_address.city,
					billing_zip_code: default_address.zip_code,

					is_address_saved: true
				)
			end
		end
	end
	def payment
		 cart_item = current_user.addresses.where(id: params[:cart_id])
		unless current_cart.is_address_saved
			default_address = current_user.default_address
		end
	end

	def set_address
		address = current_user.addresses.where(id: params[:cart_id]).first
		if address.present?
			current_cart.update(
				name: address.name,
				mobile: address.mobile,
				address_line_1: address.address_line_1,
				address_line_2: address.address_line_2,
				country: address.country,
				state: address.state,
				city: address.city,
				zip_code: address.zip_code,
				payment: payment,
				is_address_saved: true
			)
		end
		redirect_to cart_review_path(current_cart)
	end

	def new_address
		@cart = Cart.new

    @countries = CS.countries.map{|c| [c.last, c.last]}

    country_code = CS.countries.to_a.select{|i| i[1] == "India"}[0][0]

    @states_hash = CS.states(country_code)
    @states_hash[:AN] = "Andaman and Nicobar Islands"
    @states_hash[:PY] = "Puducherry"
    @states_hash[:CT] = "Chhattisgarh"
    @states_hash[:HP] = "Himachal Pradesh"
    @states_hash[:JH] = "Jharkhand"
    @states_hash[:PB] = "Punjab"
    @states_hash[:DL] = "Delhi"
    @states_hash[:LD] = "Lakshadweep"
    @states = CS.states(country_code).map{|c| [c.last, c.last]}

    
    @cities = {}

		render "address"
	end

	def edit_address
		@cart = current_cart

		@countries = CS.countries.map{|c| [c.last, c.last]}
    country = @cart.country
    country_code = CS.countries.to_a.select{|i| i[1] == country}[0][0]
    @states_hash = CS.states(country_code)
    if country = "India"
      @states_hash[:AN] = "Andaman and Nicobar Islands"
      @states_hash[:PY] = "Puducherry"
      @states_hash[:CT] = "Chhattisgarh"
      @states_hash[:HP] = "Himachal Pradesh"
      @states_hash[:JH] = "Jharkhand"
      @states_hash[:PB] = "Punjab"
      @states_hash[:DL] = "Delhi"
      @states_hash[:LD] = "Lakshadweep"
    end
    @states = CS.states(country_code).map{|c| [c.last, c.last]}
    state = @cart.state
    state_code = @states_hash.to_a.select{|i| i[1] == state}[0][0] rescue nil
    @cities = CS.cities(state_code, country_code)
    @cities.delete_if{|i|i=="Delhi"}
    @cities.delete_if{|i|i=="Haryana"}
    @cities.delete_if{|i|i=="Goa"}
		render "address"
	end

	def update_address
		current_cart.update(cart_params)
		current_cart.update(is_address_saved: true)
		if params[:cart][:checkout_address_type] == "new_address"
			address = current_user.addresses.build(cart_params)
			address.save
		end
		redirect_to cart_review_path(current_cart)
	end

	def set_billing_address
		address = current_user.addresses.where(id: params[:cart_id]).first
		if address.present?
			current_cart.update(
				billing_name: address.name,
				billing_mobile: address.mobile,
				billing_address_line_1: address.address_line_1,
				billing_address_line_2: address.address_line_2,
				billing_country: address.country,
				billing_state: address.state,
				billing_city: address.city,
				billing_zip_code: address.zip_code,
				is_address_saved: true
			)
		end
		redirect_to cart_review_path(current_cart)
	end

	def new_billing_address
		@cart = Cart.new

    @countries = CS.countries.map{|c| [c.last, c.last]}
    @states = {}
    @cities = {}

		render "billing_address"
	end

	def edit_billing_address
		@cart = current_cart

		@countries = CS.countries.map{|c| [c.last, c.last]}
    country = @cart.billing_country
    country_code = CS.countries.to_a.select{|i| i[1] == country}[0][0]
    @states_hash = CS.states(country_code)
    @states = CS.states(country_code).map{|c| [c.last, c.last]}
    state = @cart.billing_state
    state_code = @states_hash.to_a.select{|i| i[1] == state}[0][0]
    @cities = CS.cities(state_code, country_code)

		render "billing_address"
	end

	def update_billing_address
		current_cart.update(cart_params)
		current_cart.update(is_address_saved: true)
		redirect_to cart_review_path(current_cart)
	end

	private

    def cart_params
      params.require(:cart).permit(:name, :mobile, :email, :address_line_1, :address_line_2, :landmark, :country, :state, :city, :zip_code, :billing_name, :billing_mobile, :billing_address_line_1, :billing_address_line_2, :billing_country, :billing_state, :billing_city, :billing_zip_code, :payment)
    end

    def cart_item_params
      params.require(:cart_item).permit(:quantity, :comment,
        :documents_attributes => [:id, :doc, :docable]
      )
    end
	
end

app/views/carts/_cart_item.html.erb
<div class="row">
  <div class="col-md-3"><%= raw item.product.category.category_desc rescue nil %></div>
  <div class="col-md-5">
    <div class="row">
      <div class="col-md-6"><h5>Rate</h5></div>
      <div class="col-md-6"><h5>Quantity</h5></div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="row">
      <div class="col-md-9"><h5>Subtotal</h5></div>
      <div class="col-md-3"><h5>Delete</h5></div>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-12 col-sm-12 col-md-3 text-center1">
    <h4 class="product-name"><strong><%= link_to item.product.name, product_path(item.product) %></strong></h4>
    <%= link_to image_tag(item.product.image_url(:thumb), class: "img-fluid"), product_path(item.product), width: 140, height: 140 %>
  </div>
  <div class="size_block1 col-12 col-sm-12 col-md-5">
    <div class="row" style="height:65px;">
      <div class="size_block1 col-12 col-sm-12 col-md-6">
        <strong>
          <%= item.price.currency.symbol %> <%= item.display_price %>
          <% if item.product.discount_percentage %>
            <div class="discount"><%= item.product.discount_percentage.to_i %>%  off</div>
          <% end %>
        </strong>
      </div>
      <div class="size_block1 col-12 col-sm-12 col-md-6">
        <%= form_for item, url: cart_update_item_path(item), method: :post, remote: true do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          <div class="form-group">
            <%= f.number_field :quantity, style: "width:46px; height:38px; margin:0 5px;", class: "text-center quantity-box", min: 1, oninput: "submit_item_form(#{item.id});" %>
            <%= item.product.uom.name rescue nil %>
            <div class="pt-10">
              <a href="javascript:void(0)" class="btn-outline-default btn-qty" onclick="decrease_qty(<%= item.id %>);"><i class="fa fa-minus" aria-hidden="true"></i></a>
              <a href="javascript:void(0)" class="btn-outline-default btn-qty" onclick="increase_qty(<%= item.id %>);"><i class="fa fa-plus" aria-hidden="true"></i></a>
            </div>
            <!-- &nbsp; -->
            <%#= button_tag(class: "btn-outline-default btn-xs", title: "Update", "data-toggle": "tooltip") do %>
              <!-- <i class="fa fa-refresh" aria-hidden="true"></i> -->
            <%# end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="size_block1 col-12 col-sm-12 col-md-12">
        <%= form_for item, url: cart_update_item_comment_path(item), html: {id: "item_comment_form_#{item.id}"}, method: :post, remote: true do |f| %>
          <%= f.hidden_field :item_id, value: item.id %>
          <div>
            <h5 class="text-left">Comment</h5>
            <%= f.text_area :comment, class: "form-control comment_field", rows: 4, onchange: "submit_item_comment_form(#{item.id});" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="size_block1 col-12 col-sm-12 col-md-4">
    <div class="row" style="height:65px;">
      <div class="size_block1 col-12 col-sm-12 col-md-9">
        <strong><%= item.price.currency.symbol %> <%= item.display_subtotal %></strong>
      </div>
      <div class="col-12 col-sm-12 col-md-3">
        <a href="<%= cart_remove_item_path(item) %>" data-method="delete">
          <button type="button" class="btn-outline-danger btn-xs">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </button>
        </a>
        <!-- <div class="col-2 col-sm-2 col-md-2 text-right">
          <a href="<%= cart_remove_item_path(item) %>" data-toggle="tooltip" title="Delete Item" data-method="delete">
            <button type="button" class="btn-outline-danger btn-xs">
              <i class="fa fa-trash" aria-hidden="true"></i>
            </button>
          </a>
        </div> -->
        <%#= form_for item, url: cart_update_item_path(item), method: :post do |f| %>
          <!-- <h5 class="text-left">Comment: </h5> -->
          <%#= f.text_area :comment, class: "form-control", style: "margin-left:25px;", disable: true %>
        <%# end %>
      </div>
    </div>
    <div class="row">
      <div class="size_block1 col-12 col-sm-12 col-md-12">
        <%= form_for item, url: cart_update_item_path(item), method: :post, html: {"data-id": item.id, id: "item_doc_form_#{item.id}"}, remote: true do |f| %>
          <%#= f.hidden_field :item_id, value: item.id %>
          <div>
            <h5 class="text-left">File Upload</h5>
            <% item.documents.build if item.documents.blank? %>
            <div class="form-group">
              <%= f.fields_for :documents do |a| %>
                <div class="row text-box-<%= item.id %>">
                  <div class="col-md-4 file-upload">
                    <%= a.file_field :doc, class: "form-control doc_field", onchange: "submit_item_doc_form(#{item.id});", "data-cart-item-id": item.id, id: "cart_item_#{item.id}_documents_attributes_#{a.index}_doc" %>
                    <%= a.label :doc, "File Upload", class: "btn btn-default", for: "cart_item_#{item.id}_documents_attributes_#{a.index}_doc", "data-toggle": "tooltip", title: "You may upload any documents such as word, excel, PDF, video, images related to your requirement." %>
                  </div>
                  <div class="col-md-5 doc-file-name">
                    <span data-toggle="tooltip" title="<%= a.object.doc.file.filename rescue nil %>"><%= a.object.doc.file.filename.truncate(17) rescue nil %></span>
                  </div>
                  <div class="col-md-3">
                    <% if a.object.id.present? %>
                      <%= link_to "Delete", cart_delete_item_doc_path(item, doc: a.object), data: {method: :delete, remote: true} %>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
            <% if item.documents.count < 3 %>
              <a class="add-box" href="javascript:void(0)" onclick="add_more('<%= item.id %>');">Add More</a>
            <% end %>

          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<hr>

app/views/carts/_cart_subtotal.html.erb
<div class="form-group">
  <div class="col-xs-12">
    <b>Subtotal</b>
    <div class="pull-right"><span><%= current_cart.subtotal.currency.symbol %></span><span><%= current_cart.subtotal %></span></div>
  </div>
</div>
<hr>
<div class="form-group">
  <div class="col-xs-12">
    <b>Total Price</b>
    <div class="pull-right">
      <span><%= current_cart.total.currency.symbol %></span>
      <span><%= current_cart.total %></span>
    </div>
  </div>
  <small>* Price is inclusive of all taxes</small>
</div>

app/views/carts/address.js.slim
|
	$("#address-popup").modal("show")
	$('#address-popup').html("#{escape_javascript(render 'address_form')}");

app/views/carts/billing_address.js.slim
|
	$("#billing-address-popup").modal("show")
	$('#billing-address-popup').html("#{escape_javascript(render 'billing_address_form')}");

app/views/carts/delete_item_doc.js.erb
$("#cart_item_<%= @cart_item.id %>").html("<%= escape_javascript(render 'cart_item', item: @cart_item) %>");

app/views/carts/index1.html.erb
<div class="container pt-40 pb-40">
  <div class="row pb-10">
    <div class="col-md-4 pt-1">
      <a href="/" class="btn btn-default2 text-uppercase"><span class="fa fa-chevron-left"></span> Continue Shopping</a>
    </div>

   <!--  <div class="col-md-4 pt-1">
      <a href="/" data-toggle="tooltip" title="Continue Shopping">
        <button class="btn btn-default">
          <i style="font-size:24px" class="fa">&#xf104; Continue Shopping</i>
        </button>
      </a>
    </div> -->
    <div class="col-md-4 pt-1 text-center">
      <h1 class="text-center"><i class="fa fa-shopping-cart"></i> My Enquiry</h1>
      <!-- <h2><i class="fa fa-shopping-cart"></i> My Enquiry</h2> -->
    </div>
    <% if current_cart.cart_items.present? %>
      <div class="col-md-4 d-flex justify-content-end align-items-center">
        <a href="<%= cart_review_path(current_cart) %>" class="btn btn-default2 text-uppercase">Review ENQUIRIES</a>
      </div>
    <% end %>
  </div>

  <% if current_cart.cart_items.present? %>
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-3"></div>
      <div class="col-md-2"><h4>Price</h4></div>
      <div class="col-md-2"><h4>Subtotal</h4></div>
      <div class="col-md-3"></div>
    </div>
    <!-- <h4 style="padding-left: 486px;">Price</h4> -->
    <div class="card shopping-cart">
      <div class="card-body">
        <% current_cart.cart_items.each do |cart_item| %>
          <div class="row">
            <div class="col-12 col-sm-12 col-md-2 text-center">
              <%= link_to image_tag(cart_item.product.image_url(:thumb), class: "img-fluid"), product_path(cart_item.product), width: 140, height: 140 %>
            </div>

            <div class="size_block1 col-12 col-sm-12 col-md-3">
              <h4 class="product-name"><strong><%= cart_item.product.name %><% @product = Product.find(cart_item.item_id) %></strong></h4>
            </div>
            <div class="size_block1 col-12 col-sm-12 col-md-2">
              <strong><%= cart_item.price.currency.symbol %> <%= cart_item.display_price %></strong>
            </div>
            <div class="size_block1 col-12 col-sm-12 col-md-2">
              <strong><%= cart_item.price.currency.symbol %> <%= cart_item.display_subtotal %></strong>
            </div>
            <div class="col-12 col-sm-12 text-sm-center col-md-3 text-md-right row">
              <%= form_for cart_item, url: cart_update_item_path(cart_item), method: :post do |f| %>
                <%= f.hidden_field :cart_item_id, value: cart_item.id %>
                <div class="form-group">
                  <%= f.label :quantity, "Qty:", style: "font-size:20px;" %>
                  <%#= f.text_field :quantity, style: "width:38px; height:38px; margin-left:14px;", class: "text-center" %>

                  <%= f.number_field :quantity, style: "width:38px; height:38px; margin-left:14px;", class: "text-center", min: 1 %>
                  <%= cart_item.product.uom_id.present? ? Uom.find(cart_item.product.uom_id).try(:name) : '' %>
                  &nbsp;
                  <%= button_tag(class: "btn-outline-default btn-xs", title: "Update", "data-toggle": "tooltip") do %>
                    <i class="fa fa-refresh" aria-hidden="true"></i>
                  <% end %>
                  <a href="<%= cart_remove_item_path(cart_item) %>" data-toggle="tooltip" title="Delete Item" data-method="delete">
                    <button type="button" class="btn-outline-danger btn-xs">
                      <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                  </a>
                </div>
                <br>
                <div>
                  <h5 class="text-left">Comment: </h5>
                  <%= f.text_area :comment, class: "form-control" %><br>
                  <%= f.submit "Update", class: "btn btn-primary", style: "padding:6px 20px;" %>
                </div>
              <% end %>
              <!-- <div class="col-2 col-sm-2 col-md-2 text-right">
                <a href="<%= cart_remove_item_path(cart_item) %>" data-toggle="tooltip" title="Delete Item" data-method="delete">
                  <button type="button" class="btn-outline-danger btn-xs">
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  </button>
                </a>
              </div> -->
              <%#= form_for cart_item, url: cart_update_item_path(cart_item), method: :post do |f| %>
                <!-- <h5 class="text-left">Comment: </h5> -->
                <%#= f.text_area :comment, class: "form-control", style: "margin-left:25px;", disable: true %>
              <%# end %>
            </div>
          </div>
          <hr>
        <% end %>
        <div>
          <div class="row">
            <div class="col-lg-4">
            </div>
            <div class="col-lg-4">
            </div>
            <div class="col-lg-4">
              <div class="form-group text-right"></div>
              <div class="form-group">
                <div class="col-xs-12">
                  <b>Subtotal</b>
                  <div class="pull-right"><span><%= current_cart.subtotal.currency.symbol %></span><span><%= current_cart.subtotal %></span></div>
                </div>
                <!-- <div class="col-xs-12">
                  <small>Shipping</small>
                  <div class="pull-right"><span>-</span></div>
                </div> -->
              </div>
              <div class="form-group">
                <hr />
              </div>
              <div class="form-group">
                <div class="col-xs-12">
                  <b>Total Price</b>
                  <div class="pull-right">
                    <span><%= current_cart.total.currency.symbol %></span>
                    <span><%= current_cart.total %></span>
                  </div>
                </div>
                <small>* Price is inclusive of all taxes</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div>
      <h3 class="text-center">Your Cart is empty</h3>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();
  });
</script>

<style type="text/css">
  .btn-outline-danger, .btn-outline-default{padding: 0.375rem 0.75rem;}
  input[type=number]::-webkit-inner-spin-button, 
  input[type=number]::-webkit-outer-spin-button { 
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
      margin: 0; 
  }
  .size_block
  {
    min-width: 289px;
    max-width: 290px;
  }
</style>

app/views/carts/payment.html.erb
<section class="contact-sec page-section-pt">
  <div class="check">
    <div class="section-title text-center">
      <h1 class="text-center">Payment Information</h1>
      <h3>Coming Soon...</h3>
      <%= form_for @cart, url: cart_update_address_path, html: {id: "new_address_form"}, method: :post do |f| %>
        <% if current_cart.payment == 1 %>
         <h3>cash on delivery</h3>
        <%end%>
        <% if current_cart.payment == 2 %>
         <h3>card</h3>
        <%end%> 
        <% if current_cart.payment == 3 %>
         <h3>Stripe</h3>
        <%end%> 
        <% if current_cart.payment == 3 %>
         <h3>Paypal</h3>
        <%end%> 
        
        <%#= f.collection_radio_buttons :payment, Cart::PAYMENT, :first, :last, include_hidden: true, class: "new"  %> 
        <%end%>
    </div>
  </div>
</section>
<style type="text/css">
  #new{
    width: 2px;
  }
</style>

app/views/carts/update_item.js.erb
$("#cart_item_<%= @cart_item.id %>").html("<%= escape_javascript(render 'cart_item', item: @cart_item) %>");
$("#cart_subtotal").html("<%= escape_javascript(render 'cart_subtotal', item: @cart_item) %>");