config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: {omniauth_callbacks: "users/omniauth_callbacks", registrations: "users/registrations", confirmations: 'users/confirmations'}

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # get 'pages/index'
	root "pages#index"
  #get "/pages/:show/:mainid/:category_id" => "blogs#category", as: :blogs_category
  get "/search" => "products#search"

  get "/ajaxValidateFieldUser" => "dashboard#verify_password"


  get "/about" => "pages#about"
  get "/how-we-work" => "pages#how_we_work"
  get "/wishlist" => "pages#wishlist"

  # get "/services" => "pages#services"
  get "/careers" => "pages#careers"
  get "/contact-us" => "pages#contact_us"
  post "/contact-us" => "pages#contact_us_submit"


  post "/quote" => "pages#quote", as: :quote
  post "/news_letter" => "pages#news_letter"
  get "/unsubscribe/:code" => "pages#unsubscribe"
  get "/sitemap" => "pages#sitemap"
  post "/get_in_touch" => "pages#get_in_touch"

  scope "blogs" do
    get "/" => "blogs#index"
    get "/:id" => "blogs#show", as: :blog
    get "/category/:service_category_id" => "blogs#service_category", as: :blogs_service_category
    get "/category/:service_category_id/:main_category_id" => "blogs#main_category", as: :blogs_main_category
    get "/category/:service_category_id/:main_category_id/:category_id" => "blogs#category", as: :blogs_category
  end

  resources :carts, only: :index do
    post :add_item
    post :update_item
    post :update_item_comment
    delete :delete_item_doc
    delete :remove_item
    get :review
    get :payment
    get :set_address
    get :edit_address
    get :new_address
    post :update_address
    get :set_billing_address
    get :new_billing_address
    get :edit_billing_address
    post :update_billing_address
  end

  resources :orders, only: :create

  resources :categories, only: :index do
    get "products"
    get "quote"
    post "custom_quote"
    get "get_main_categories"
    get "get_categories"

    get "/:main_category_id/:category_id/products" => "categories#products"
    get "/:main_category_id/:category_id/quote" => "categories#quote"


    # get "/get_main_category/:service_category_id" => "categories#get_main_category"
  end

  resources :products, only: :show do
  end

  get "/products/:service_category_id/:main_category_id/:category_id/:id" => "products#show", as: :show

  # scope "categories" do
  #   get "/:id/products" => "categories#products", as: :products
  # end
  

  namespace :dashboard do
    get '', action: :index
    post '/profile_pic/update', action: :update_profile_pic, as: :update_profile_pic
    post '/profile/update', action: :update_profile, as: :update_profile
    post '/mobile/update', action: :update_mobile, as: :update_mobile
    post '/otp/verify', action: :verify_otp, as: :verify_otp

    post '/update_password', action: :update_password, as: :update_password

    get "/address/new", action: :new_address, as: :new_address
    get "/address/:id/edit", action: :edit_address, as: :edit_address
    post '/address/create', action: :create_address, as: :create_address
    get "/address/:id/set_default_address", action: :set_default_address, as: :set_default_address
    delete "/address/:id", action: :delete_address, as: :delete_address
    post "create_vendor"
    post :business_profile
    post :expertise
    post :capacity
    post :legal

    get :new_project
    get "/project/:id/edit", action: :edit_project, as: :edit_project
    post :projects
    delete "/project/:id/edit", action: :delete_project, as: :delete_project

    get :new_employment
    get "/employment/:id/edit", action: :edit_employment, as: :edit_employment
    post :employments
    delete "/employment/:id/edit", action: :delete_employment, as: :delete_employment

    get :new_education
    get "/education/:id/edit", action: :edit_education, as: :edit_education
    post :educations
    delete "/education/:id/edit", action: :delete_education, as: :delete_education

    post "/wishlist/:id", action: :add_wishlist, as: :add_wishlist
    post "/deactivate", action: :deactivate, as: :deactivate
    post "/reactivate", action: :reactivate, as: :reactivate


  end

  resources :vendors do
    post :update
  end


  delete "remove_wishlist_item/:slug" => "dashboard#remove_wishlist_item", as: :remove_wishlist_item
  

  get "/get_states/:country" => "pages#get_states"
  get "/get_cities/:state/:country" => "pages#get_cities"
  get '/dashboard/preview_profile'
  get '/carts/payment'
  get '/career/:id' => "pages#career"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

	include Statusable

	extend FriendlyId
  friendly_id :name, use: [:slugged, :finders]

  # TYPE = {1 => "MMB Supplied", 2 => "Custom"}

	belongs_to :category
  # belongs_to :uom, optional: true

	validates_presence_of :name, :category_id

  validates_numericality_of :rank, greater_than_or_equal_to: 1

	has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true

  has_many :attributs, through: :category

  has_many :cart_items, as: :item, dependent: :destroy
  has_many :recent_products, dependent: :destroy

  # has_many :attributables, as: :attributable, dependent: :destroy
  # has_many :attributables, through: :category

  # has_many :attributs, through: :attributables
  # accepts_nested_attributes_for :attributables, allow_destroy: true

  delegate :main_category, to: :category, allow_nil: true
  delegate :service_category, to: :main_category, allow_nil: true

  delegate :uom, to: :category, allow_nil: true

  has_many :attribute_values, as: :valueable, dependent: :destroy
  accepts_nested_attributes_for :attribute_values

  mount_uploader :image, ProductImageUploader
  mount_uploader :image1, ProductImageUploader
  mount_uploader :image2, ProductImageUploader
  mount_uploader :image3, ProductImageUploader
  mount_uploader :image4, ProductImageUploader
  has_many :uoms, as: :uomable#, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  accepts_nested_attributes_for :uoms, allow_destroy: true

  after_save :update_cart

  def display_price
    result = ""
    if self.price.to_f > 0
      result += "#{self.price.to_i}"
      result += "/#{self.uom.name}" if self.uom.present?
      # "/#{self.uom_id.present? ? Uom.find(self.uom_id).try(:name) : ''}"
    else
      result += "Upon Enquiry"
    end
    return result
  end

  def display_full_price
    result = ""
    if self.full_price.to_f > 0
      result += "#{self.full_price.to_i}"
      result += "/#{self.uom.name}" if self.uom.present?
      # "/#{self.uom_id.present? ? Uom.find(self.uom_id).try(:name) : ''}"
    else
      result += "Upon Enquiry"
    end
    return result
  end

  def category_desc
    result = ""
    result += "<a href='/categories?scrollto=service-category-#{service_category.id}&service_category=#{service_category.id}'>#{service_category.short_name}</a> >> " if service_category.present?
    result += "<a href='/categories?scrollto=main-category-#{main_category.id}&service_category=#{service_category.id}'>#{main_category.short_name}</a> >> " if main_category.present?
    result += "<a href='#{category.url}'>#{category.name}</a>" if category.present?
  end

  def discount_percentage
    if price.present? && price > 0 && full_price.present? && full_price > 0
      " " + (100 - (price.to_f / full_price.to_f * 100.0)).to_s + "%"
      # "Discount: " + (100 - (price.to_f / full_price.to_f * 100.0)).to_s + "%"
    else
      nil
    end
  end

  def update_cart
    if price_changed?
      cart_item_ids = Cart.where(is_ordered: false).collect(&:cart_items).flatten.map(&:id)
      cart_items = CartItem.where(id: cart_item_ids, item_id: self.id, item_type: "Product")
      cart_items.each do |cart_item|
        cart_item.update(price: self.price)
      end
    end
  end

  def share_title
    "#{service_category.name} >> #{main_category.name} >> #{category.name} >> #{name}"
  end

  def type_name
    category.type_name
  end

  def parent_terms
    "#{service_category.try(:terms)} #{main_category.try(:terms)} #{category.try(:terms)}"
  end

  def all_terms
    "#{service_category.try(:terms)} #{main_category.try(:terms)} #{category.try(:terms)} #{terms_and_conditions}"
  end

  def url
    "/products/#{self.service_category.slug}/#{self.main_category.slug}/#{self.category.slug}/#{self.slug}"
  end

  ransacker :uom, formatter: proc {|value|
    results = Uom.find(value).categories.map(&:products).flatten.compact.map(&:id) # return only id-s of returned items.
    results.present? ? results : nil
  } do |parent|
    parent.table[:id]
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	def show
		@product = Product.find(params[:id])
		@category = @product.category
		if user_signed_in?
			current_user.recent_products.where(product_id: @product.id).destroy_all
			RecentProduct.create(user_id: current_user.id, session_id: session.id, product_id: @product.id)
		else
			RecentProduct.where(session_id: session.id, product_id: @product.id).destroy_all
			RecentProduct.create(session_id: session.id, product_id: @product.id)
		end
	end

	def search
		search = params[:q].downcase rescue nil
		categories = Category.active.where("lower(name) like '%#{search}%'")
		categories_products_ids = categories.map(&:products).flatten.map(&:id)
		products_ids = Product.active.where("lower(name) like '%#{search}%' OR lower(products.desc) like '%#{search}%'").map(&:id)
		unique_ids = (categories_products_ids + products_ids).uniq
		@products = Product.where(id: unique_ids).active.paginate(:page => params[:page], :per_page => 6)
		if params[:sort] == "1"
			@products = @products.order("price asc")
		elsif params[:sort] == "2"
			@products = @products.order("price desc")
		elsif params[:sort] == "3"
			@products = @products.order("created_at desc")
		end
	end

end

app/views/products/_index.html.erb
<% @products.order(:name).each do |product| %>
  <div class="row">
    <div class="col-md-6 col-sm-6 col-lg-6">
      <div class="container container1">
        <%= link_to image_tag(product.image_url(:large), class: "image"), product.url %>
        <div class="middle">
          <h4><%= link_to product.name, product.url, class: "text-white" %></h4>
        </div>
      </div>
    </div>
    <div class="col-md-6 col-sm-6 col-lg-6">
      <div><h4><%= link_to product.name, product.url %></h4></div>
      <% if params[:action] == "search" %>
        <div><h5><%= raw product.category_desc %></h5></div>
      <% end %>
      <!-- <div display="table-row"><%= product.desc.truncate(200).html_safe rescue nil %></div> -->
      <div display="table-row" style="cursor:pointer;" onclick="window.location='<%= product.url %>';">
        <%#= truncate(product.desc, length: 200, omission: "..." , escape: false) %>
        <%#= raw Truncato.truncate product.desc, max_length: 200 rescue nil %>
        <%= ActionView::Base.full_sanitizer.sanitize(product.desc).truncate(200) rescue nil %>
        <%= link_to "Read More", product.url, class: "text-blue" %>
      </div>
      <!-- <div>Price: <%= product.display_price %></div>
      <div>Full Price: <%= product.display_full_price %></div> -->
      <span class="price h4 display_color">
        <strong>₹ <%= product.display_price %> </strong>
      </span>
      <% if product.full_price.to_f > 0 %>
        <del> ₹<%= product.display_full_price %></del>  &nbsp;&nbsp;
      <% end %>
      <% if product.discount_percentage %>
        <span class="discount"><%= product.discount_percentage.to_i %>%  off</span>
      <% end %>
      <div class="d-flex justify-content-center" align="text-center">
        <%= form_for :cart_item, url: cart_add_item_path(product) do |f| %>
          <%= f.hidden_field :product_id, value: product.slug %>
          <%= f.hidden_field :quantity, value: 1 %>
          <%= button_tag(type: 'submit', class: "btn btn-default1 box_size") do %>
            <i class="fa fa-shopping-cart"></i> Send Enquiry
          <% end %>
          <% if Wishlist.where(user_id: current_user.try(:id), product_id: product).present? %>
            <%= link_to remove_wishlist_item_path(product), class: "btn btn-default1 box_size", data: {method: :delete, remote: true} do %>
              <i class="fa fa-heart-o"></i> Remove From Wishlist
            <% end %>
          <% else %>
            <%= link_to dashboard_add_wishlist_path(product), class: "btn btn-default1 box_size", data: {method: :post, remote: true} do %>
              <i class="fa fa-heart"></i> Add to Wishlist
            <% end %>
          <% end %>  
        <% end %>
      </div>
    </div>
  </div>
<% end %>
<div class="row pull-right">
    <ul class="pagination pg-blue justify-content-end page pagination_bg_color pre_next_format">
    <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
  </ul>
</div>

app/views/products/_recently_viewed.html.erb
<h3>RECENTLY VIEWED</h3>
<div class="owl-carousel owl-theme">
  <% products.each_with_index do |product, index| %>
    <div class="item" onclick="window.location='<%= product.url %>';">
      <div class="panel panel-default">
        <div class="container1 panel-thumbnail">
          <%= link_to image_tag(product.image_url(:thumb), class: "img-fluid mx-auto d-block img_size"), product.url, class: "thumb" %>
          <div class="product-title" style="text-align: center;"><%= product.name %> </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<br><br>

<script type="text/javascript">
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    autoplayTimeout:2000,
    // autoplayHoverPause:true,
    nav:true,
    dots: false,
    responsive:{
      0:{
          items:1
      },
      600:{
          items:3
      },
      1000:{
          items:4
      }
    },
    navText : ["<a class='carousel-control-prev' role='button' data-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='sr-only'>Previous</span></a>","<a class='carousel-control-next' role='button' data-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='sr-only'>Next</span></a>"]
  })
</script>

app/views/products/_related.html.erb
<h3>RELATED PRODUCTS</h3>
<div class="owl-carousel owl-theme">
  <% products.each_with_index do |product, index| %>
    <div class="item" onclick="window.location='<%= product.url %>';">
      <div class="panel panel-default">
        <div class="container1 panel-thumbnail">
          <%= link_to image_tag(product.image_url(:thumb), class: "img-fluid mx-auto d-block img_size"), product.url, class: "thumb" %>
          <div class="product-title" style="text-align: center;"><%= product.name %> </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<script type="text/javascript">
  $('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    autoplayTimeout:2000,
    // autoplayHoverPause:true,
    nav:true,
    dots: false,
    responsive:{
      0:{
          items:1
      },
      600:{
          items:3
      },
      1000:{
          items:4
      }
    },
    navText : ["<a class='carousel-control-prev' role='button' data-slide='prev'><span class='carousel-control-prev-icon' aria-hidden='true'></span><span class='sr-only'>Previous</span></a>","<a class='carousel-control-next' role='button' data-slide='next'><span class='carousel-control-next-icon' aria-hidden='true'></span><span class='sr-only'>Next</span></a>"]
  })
</script>

app/views/products/search.html.erb
<div class="container pb-40">
  <div class="row pb-10">
    <div class="col-md-12 pt-1 text-center">
      <h3 class="text-center"><%= @products.count %> Products found with keyword "<%= params[:q] %>"</h3>
    </div>
  </div>
  <% if @products.any? %>
    <div class="container">
      <div class="row-breadcrumbs">
        <div class="sort text-right">
          <span>Sort by:</span>
          <%= link_to "Price (Low to High)", "/search?q=#{params[:q]}&sort=1", class: "#{params[:sort] == '1' ? 'disabled' : ''}" %>
          <%= link_to "Price (High to Low)", "/search?q=#{params[:q]}&sort=2", class: "#{params[:sort] == '2' ? 'disabled' : ''}" %>
          <%= link_to "Newest First", "/search?q=#{params[:q]}&sort=3", class: "#{params[:sort] == '3' ? 'disabled' : ''}" %>
        </div>
      </div>
    </div>
  <% end %>

  <%= render "products/index" %>
  
</div>

<style type="text/css">
  .btn.btn-default1
  {
    font-size: 10px;
    margin-top: 34px;
  }
  .image{
    /*width: 100%;*/
    width: 350px;
    height: 300px;
  }
  h4{
    line-height: 50px;
    color: black;
    text-align: left;
  }
  body
  {
    text-align: center;
  }
  p{
    text-align: left;
  }
  *{
    text-align: left;
  }
  .justify-content-center{
    justify-content: left !important;
  }
  /*.paginationw a:not(.active) {background-color: #e8e8e8;}
  .paginationw a:hover:not(.active) {background-color: green;
  }*/
  .display_color
  {
    color: black;
  }
  .discount
  {
    color: green;
  }
  .box_size
  {
    width: 155px;
    height: 50px;
  }
  /*.paginationw>li>a, .pagination>li>span { border-radius: 50% !important;margin: 0 5px;}*/
</style>

app/views/products/show.html.erb
<% content_for :meta_title, @product.meta_title %>
<% content_for :meta_description, strip_tags(@product.meta_description) %>
<% content_for :meta_image, @product.image_url %>
<% content_for :meta_keywords, strip_tags(@product.meta_keywords) %>
<div class="container pt-40">
  <ul class="h6">
    <p>
    <a href="/categories?scrollto=service-category-<%= @category.service_category.id %>"><%= @category.service_category.name %></a> >> <a href="/categories?scrollto=main-category-<%= @category.main_category.id %>"><%= @category.main_category.name %></a> >> <a href="<%= @category.url %>"><%= @category.name %></a> >> <a href="#"><%= @product.name %></a>
    <!-- <li class="breadcrumb-item"><a href="/categories?scrollto=service-category-<%#= @category.service_category.id %>"><%#= @category.service_category.name %></a></li>
    <li class="breadcrumb-item"><a href="/categories?scrollto=main-category-<%#= @category.main_category.id %>"><%#= @category.main_category.name %></a></li>
    <li class="breadcrumb-item"><a href="<%#= @category.url %>"><%#= @category.name %></a></li>
    <li class="breadcrumb-item active"><a href="#"><%#= @product.name %></a></li> -->
  </p>
  </ul>

</div>

<div class="container product category_path">
  <div class="card">
    <div class="row">
      <aside class="col-lg-5 border-right">
        <article class="specs">
          <div class="img-big-wrap">
            <div>
              <%= link_to image_tag(@product.image_url, class: "image img-fluid", original_img_url: @product.image.url), "javascript:void(0)" %>
            </div>
          </div>
          <div class="aa">
            <ul class="list">
              <!-- <li>
                <span><%= link_to image_tag(@product.image1_url(:thumb), original_img_url: @product.image1.url), "javascript:void(0)" %></span>
                <span><%= link_to image_tag(@product.image2_url(:thumb), original_img_url: @product.image2.url), "javascript:void(0)" %></span>
                <span><%= link_to image_tag(@product.image3_url(:thumb), original_img_url: @product.image3.url), "javascript:void(0)" %></span>
                <span><%= link_to image_tag(@product.image4_url(:thumb), original_img_url: @product.image4.url), "javascript:void(0)" %></span>
              </li> -->
              <li>
                <% @product.images.each do |image| %>
                  <span><%= link_to image_tag(image.image_url(:thumb), original_img_url: image.image.url), "javascript:void(0)" %></span>
                <% end %>
              </li>
            </ul>
          </div>

          <!-- PRODUCT DESCRIPTION -->
          <div class="container desc">
            <div class="jumbotron">
              <div class="product_des">
                <h6>SPECIFICATIONS</h6>
                <%# @product.attribute_values.each do |attribute_value| %>
                  <!-- <div class="row">
                    <div class="col-md-6"><strong><%#= attribute_value.attribut.name %>:</strong> </div>
                    <div class="col-md-6"><%#= attribute_value.value %></div>
                  </div> -->
                <%# end %>
                <% @product.attributs.each do |attribut| %>
                  <div class="row">
                    <div class="col-md-6"><strong><%= attribut.name %>:</strong> </div>
                    <div class="col-md-6"><%= attribut.value(@product) %></div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </article>
      </aside>
      <aside class="col-lg-7">
        <!-- <div class="share d-flex justify-content-md-right">
          <a href="#" class="btn btn-default2"><i class="fa fa-share"></i>  Share</a>
        </div> -->
        <%= form_for :cart_item, url: cart_add_item_path(@product) do |f| %>
          <%= f.hidden_field :product_id, value: @product.slug %>
          <article class="card-body p-5">
            <div class="row">
              <div class="col-md-9">
                <h1 class="title mb-3 text-left" style="margin-top:0;"><%= @product.name %></h1>
              </div>
              <div class="col-md-3 text-right">
                <div class="social-login-icons" id="social-share">
                  <div class="social-share-button">
                    <%= link_to "", "mailto:?subject=Make Me Builder; #{@product.name}&body=Hello<br>I found this on Make Me Builder!<br><a href='#{request.url}'>#{@product.name}</a>", class: "ssb-icon ssb-email" %>
                  </div>
                  <%= social_share_button_tag(@product.name, url: request.url, image: @product.image, desc: @product.name, body: "nsajb") %>
                </div>
              </div>
            </div>
            <!-- <h1 class="title mb-3"><%= @product.name %></h1> -->
            <p class="price-detail-wrap"> 
              <span class="price h4 display">
                <strong>₹ <%= @product.display_price %> </strong>
              </span>
              <% if @product.full_price.to_f > 0 %>
                <del> ₹<%= @product.display_full_price %></del>  &nbsp;&nbsp;
              <% end %>
              <% if @product.discount_percentage %>
                <span class="discount"><%= @product.discount_percentage.to_i %>%  off</span>
              <% end %>
              <!-- <span class="price h3">Rs. <%#= @product.price %>/<%#= @product.uom_id.present? ? Uom.find(@product.uom_id).try(:name) : ""%></span> -->
              <!-- <span class="price h3"><del>Suggested Price: <%= @product.display_full_price %></del></span> -->
              <!-- <del>$900</del>  -->
            </p>
            <p class="price-detail-wrap"> 
              <!-- <span class="price h3">Rs. <%#= @product.price %>/<%#= @product.uom_id.present? ? Uom.find(@product.uom_id).try(:name) : ""%></span> -->
              <!-- <span class="price h3">Offer Price: 
               ₹ <%#= @product.display_price %> <%# if @product.discount_percentage %><small>(<%#= @product.discount_percentage %>)</small><%# end %></span> -->
              <!-- <del>$900</del>  -->
            </p>
            <dl class="item-property">
              <dt>
                <h5>Description</h5>
              </dt>
              <dd>
                <p><%= raw @product.desc %></p>
              </dd>
            </dl>
            <p class="read-more-block">
              <h4>Terms And Conditions</h4>
              <span class="short-desc"><%= @product.all_terms.truncate(320) rescue nil %></span>
              <span class="long-desc tmp-hide"><%= @product.all_terms rescue nil %></span>
              <% if (@product.all_terms.length rescue 0) > 320 %>
                <a href="javascript:void(0);" class="read-more-link text-blue">Read More</a>
              <% end %>
            </p> 
            <!-- <dl class="param param-feature">
              <dt>
                <h5>Model No.</h5>
              </dt>
              <dd>12345611</dd>
            </dl> -->
            <!-- item-property-hor .// -->
            <!-- <dl class="param param-feature">
              <dt>
                <h5>Color</h5>
              </dt>
              <dd>Black and white</dd>
            </dl> -->
            <!-- item-property-hor .// -->
            <!-- <dl class="param param-feature">
              <dt>
                <h5>Delivery</h5>
              </dt>
              <dd>Russia, USA, and Europe</dd>
            </dl> -->
            <!-- item-property-hor .// -->
            <hr>
            <div class="row">
              <div class="col-lg-5">
                <dl class="quantity">
                  <!-- <dt>
                    <h4>Quantity</h4>
                  </dt> -->
                  <dd>
                    <%#= f.number_field :quantity, style: "width:58px; height:38px;", class: "text-center", min: 1, value: 1 %>
                    <%= f.hidden_field :quantity, value: 1 %>

                    <!-- <span><%= @product.uom.try(:name) %></span> -->
                  </dd>
                </dl>
                <!-- <dl>
                  <dt>
                    <h4> Comment: </h4>
                  </dt>
                  <dd>
                    <%= f.text_area :comment, class: "comment_box_size" %>
                  </dd>
                </dl> -->
              </div>
            </div>
            <div class="d-flex justify-content-center">
              <%= button_tag(type: 'submit', class: "btn btn-default1 box_size1") do %>
                <i class="fa fa-shopping-cart"></i> Send Enquiry
              <% end %>&nbsp;
              <%= link_to dashboard_add_wishlist_path, class: "btn btn-default1 box_size1", data: {method: :post, remote: true} do %>
                <i class="fa fa-heart"></i> Add to Wishlist
              <% end %>
            </div>
          </article>
        <% end %>
      </aside>
    </div>
  </div>
</div>
</br>

<!-- PRODUCT DESCRIPTION -->
<!-- <div class="container desc">
  <div class="jumbotron">
    <div class="product_des">
      <h6>SPECIFICATIONS</h6>
      <%# @product.attribute_values.each do |attribute_value| %>
        <div class="row">
          <div class="col-md-2"><%#= attribute_value.attribut.name %>: </div>
          <div class="col-md-10"><%#= attribute_value.value %></div>
        </div>
      <%# end %>
    </div>
  </div>
</div> -->

<!-- RECENTLY VIEWED -->
<% if user_signed_in? && recently_viewed_products.any? %>
  <div class="container recent text-center">
    <%= render "products/recently_viewed", products: recently_viewed_products %>
  </div>
<% end %>

<div class="modal" tabindex="-1" role="dialog" id="img-modal">
  <div class="modal-dialog" role="document" style="max-width:100%;">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center"></div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $(".specs img").click(function(){
    var original_img_source = $(this).attr("original_img_url");
    $("#img-modal").modal("show");
    $("#img-modal .modal-body").html("<img class='popup_image'>")
    $("#img-modal .modal-body img").attr("src", original_img_source);
  })

</script>
<style type="text/css">
  .comment_box_size
  {
    width: 512px;
    height: 100px;
  }
  .scroll_prev
  {
    top: 72px;
    right: 17px;
    left: -25px;
    background-color: #1b1731;
    height: 20px;
    width: 20px;
  }
  .scroll_next
  {
    top: 72px;
    /*left: -30px;*/
    background-color: #1b1731;
    height: 20px;
    width: 20px;
  }
  .scroll_prev1
  {
    top: 72px;
    right: 17px;
    background-color: #1b1731;
    height: 20px;
    width: 20px;
  }
  .scroll_next1
  {
    top: 72px;
    left: 438px;
    background-color: #1b1731;
    height: 20px;
    width: 20px;
  }
  .box_size
  {
    width: 160px;
    height: 55px;
  }
  .display
  {
    color: black;
  }
  
  .category_path
  {
    padding-top: 12px;
  }
  .h6
  {
    margin-left: 443px;
  }
  ul.list li {
    display: inline-block;
  }

  ul.list li img {
      width: calc(59%/4);
  }
  input[type=number]::-webkit-inner-spin-button, 
  input[type=number]::-webkit-outer-spin-button { 
      -webkit-appearance: none;
      -moz-appearance: none;
      appearance: none;
      margin: 0; 
  }
  .popup_image{
    max-width:100%;
  }
</style>